name: On Pull Request

on:
  pull_request:
    branches:
      - main
      - release/*

jobs:
  pack:
    uses: ./.github/workflows/test.yml
  package:
    needs: test
    uses: ./.github/workflows/package.yml
