name: On Pull Request

on:
  pull_request:
    branches:
      - main
      - release/*

jobs:
  test:
    uses: ./.github/workflows/test.yml
  package:
    needs: test
    uses: ./.github/workflows/package.yml
