name: Release

on:
  workflow_dispatch:

env:
  CONFIGURATION: 'Release'
  DOTNET_VERSION: '6.0.x'

jobs:
  test:
    uses: ./.github/workflows/test.yml
  pack:
    needs: test
    uses: ./.github/workflows/pack.yml
  release:
    needs: pack
    if: startsWith(github.ref, 'refs/heads/release/')
    runs-on: ubuntu-latest
    steps:
    - name: Download Neo.Assertions
      uses: actions/download-artifact@v3
      with:
        name: assertions
        path: ./out
    - name: Download Neo.BuildTasks
      uses: actions/download-artifact@v3
      with:
        name: build-tasks
        path: ./out
    - name: Download Neo.Test.Harness
      uses: actions/download-artifact@v3
      with:
        name: test-harness
        path: ./out
    - name: Download Neo.Test.Runner
      uses: actions/download-artifact@v3
      with:
        name: test-runner
        path: ./out
    - name: Create Release
      uses: marvinpinto/action-automatic-releases@v1.1.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: ${{ needs.pack.outputs.PrereleaseVersion != '' }}
        title: Release ${{ needs.pack.outputs.NuGetPackageVersion }}
        automatic_release_tag: ${{ needs.pack.outputs.NuGetPackageVersion }}
        files: |
          ./out/*
    - name: Push to Nuget.org
      run: dotnet nuget push ${{ format('./out/Neo.Assertions.{0}.nupkg', needs.pack.outputs.NuGetPackageVersion) }} --api-key ${{ secrets.NUGET_ORG_TOKEN }} --source https://api.nuget.org/v3/index.json
    - name: Push to Nuget.org
      run: dotnet nuget push ${{ format('./out/Neo.BuildTasks.{0}.nupkg', needs.pack.outputs.NuGetPackageVersion) }} --api-key ${{ secrets.NUGET_ORG_TOKEN }} --source https://api.nuget.org/v3/index.json
    - name: Push to Nuget.org
      run: dotnet nuget push ${{ format('./out/Neo.Test.Harness.{0}.nupkg', needs.pack.outputs.NuGetPackageVersion) }} --api-key ${{ secrets.NUGET_ORG_TOKEN }} --source https://api.nuget.org/v3/index.json
    - name: Push to Nuget.org
      run: dotnet nuget push ${{ format('./out/Neo.Test.Runner.{0}.nupkg', needs.pack.outputs.NuGetPackageVersion) }} --api-key ${{ secrets.NUGET_ORG_TOKEN }} --source https://api.nuget.org/v3/index.json
