name: Release

on:
  workflow_dispatch:

jobs:
  test:
    if: startsWith(github.ref, 'refs/heads/release/')
    uses: ./.github/workflows/test.yml
  pack:
    if: startsWith(github.ref, 'refs/heads/release/')
    uses: ./.github/workflows/pack.yml
  release:
    if: startsWith(github.ref, 'refs/heads/release/')
    needs: [test, pack]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: packages
        path: ./out
    - name: Create Release
      uses: marvinpinto/action-automatic-releases@v1.1.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: ${{ needs.pack.outputs.PrereleaseVersion != '' }}
        title: Release ${{ needs.pack.outputs.NuGetPackageVersion }}
        automatic_release_tag: ${{ needs.pack.outputs.NuGetPackageVersion }}
        files: |
          ./out/*
    - name: Push to Nuget.org
      run: dotnet nuget push out/*.nupkg --api-key ${{ secrets.NUGET_ORG_TOKEN }} --source https://api.nuget.org/v3/index.json
