name: Run Test

on:
  workflow_call:

env:
  CONFIGURATION: 'Release'
  DOTNET_VERSION: '6.0.x'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Nerdbank.GitVersioning
      uses: dotnet/nbgv@v0.4.0
      id: nbgv
    - name: Pack
      run: |
        dotnet restore
        dotnet build --configuration ${{ env.CONFIGURATION }} --no-restore --verbosity normal --BinaryLogger:./msbuild.binlog
        dotnet test --configuration ${{ env.CONFIGURATION }} --no-build --verbosity normal --collect:"XPlat Code Coverage"
    - name: Upload Build Log
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: buildlog
        path: ./msbuild.binlog
    - name: Upload Coverage
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: ./test/test.bctklib/TestResults/*/coverage.cobertura.xml
  report:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Coverage Artifact
        uses: actions/download-artifact@v3
        with:
          name: coverage
          path: ./coverage
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ./coverage/**/coverage.cobertura.xml
